
#' Patient Record Consistency -- Output Generation
#'
#' Using the tabular output generated by `prc_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_ssdqa()`
#'
#' @param process_output the summary output from `prc_process`
#' @param output_function the name of the output function that should be executed; this is provided
#'                        in a console message after `prc_process` finishes executing
#' @param dist_from_stat the statistic from which distance should be measured for ms_exp_at
#'                       acceptable values are `mean` or `median`
#' @param event_filter the event type of interest for the analysis for ss_anom_at or ms_anom_at;
#'                     can be either `a`, `b`, `both`, or `neither`
#'
#' @return a graph visualizing the output from `prc_process`; see individual functions for
#'         more specific details
#'
#' @example inst/example-prc_process_output.R
#'
#' @export
#'
prc_output <- function(process_output,
                       output_function,
                       dist_from_stat = 'mean',
                       event_filter = NULL){


  if(output_function == 'prc_ss_exp_cs'){

    prc_output <- prc_ss_exp_cs(process_output = process_output)

  }else if(output_function == 'prc_ms_exp_cs'){

    prc_output <- prc_ms_exp_cs(process_output = process_output)

  }else if(output_function == 'prc_ss_anom_cs'){

    prc_output <- prc_ss_anom_cs(process_output = process_output)

  }else if(output_function == 'prc_ms_anom_cs'){

    prc_output <- prc_ms_anom_cs(process_output = process_output)

  }else if(output_function == 'prc_ss_exp_la'){

    prc_output <- prc_ss_exp_la(process_output = process_output)

  }else if(output_function == 'prc_ms_exp_la'){

    prc_output <- prc_ms_exp_la(process_output = process_output,
                                dist_from_stat = dist_from_stat)

  }else if(output_function == 'prc_ss_anom_la'){

    prc_output <- prc_ss_anom_la(process_output = process_output,
                                 event_filter = event_filter)

  }else if(output_function == 'prc_ms_anom_la'){

    prc_output <- prc_ms_anom_la(process_output = process_output,
                                 event_filter = event_filter)

  }else{cli::cli_abort('Please enter a valid output function for this check type.')}

  return(prc_output)

}
