
#' Patient Record Consistency -- Output Generation
#'
#' Using the tabular output generated by `prc_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* | the summary output from `prc_process`
#' @param dist_from_stat *string* | the statistic from which distance should be measured for ms_exp_at
#'                       acceptable values are `mean` or `median`
#' @param event_filter *string* | the event type of interest for the analysis for ss_anom_at or ms_anom_at;
#'                     can be either `a`, `b`, `both`, or `neither`
#'
#' @return a graph visualizing the output from `prc_process`; see individual functions for
#'         more specific details
#'
#' @example inst/example-prc_process_output.R
#'
#' @export
#'
prc_output <- function(process_output,
                       dist_from_stat = 'mean',
                       event_filter = NULL){

  # extract output function
  output_function <- process_output %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()


  if(output_function == 'prc_ss_exp_cs'){

    prc_output <- prc_ss_exp_cs(process_output = process_output)

  }else if(output_function == 'prc_ms_exp_cs'){

    prc_output <- prc_ms_exp_cs(process_output = process_output)

  }else if(output_function == 'prc_ss_anom_cs'){

    prc_output <- prc_ss_anom_cs(process_output = process_output)

  }else if(output_function == 'prc_ms_anom_cs'){

    prc_output <- prc_ms_anom_cs(process_output = process_output)

  }else if(output_function == 'prc_ss_exp_la'){

    prc_output <- prc_ss_exp_la(process_output = process_output)

  }else if(output_function == 'prc_ms_exp_la'){

    prc_output <- prc_ms_exp_la(process_output = process_output,
                                dist_from_stat = dist_from_stat)

  }else if(output_function == 'prc_ss_anom_la'){

    prc_output <- prc_ss_anom_la(process_output = process_output,
                                 event_filter = event_filter)

  }else if(output_function == 'prc_ms_anom_la'){

    prc_output <- prc_ms_anom_la(process_output = process_output,
                                 event_filter = event_filter)

  }else{cli::cli_abort('Please enter a valid output function for this check type.')}

  return(prc_output)

}
