
#' Patient Record Consistency -- Output Generation
#'
#' Using the tabular output generated by `prc_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* || **required**
#'
#'   The tabular output produced by `pes_process`
#'
#'   Note any patient-level results generated are not intended to be used with this function.
#'
#' @param dist_from_stat *string* || defaults to `mean`
#'
#'   A string indicating the statistic from which distance should be measured for the
#'   `Multi-Site, Exploratory, Longitudinal` check
#'
#'   Acceptable values are `mean` or `median`
#'
#' @param event_filter *string* || defaults to `NULL`
#'
#'   A string indicating the event co-occurrence type of interest for the analysis.
#'   This parameter is required for the following checks:
#'   - `Single Site, Anomaly Detection, Longitudinal`
#'   - `Multi-Site, Anomaly Detection, Longitudinal`
#'
#'   Acceptable values are `a`, `b`, `both`, or `neither`
#'
#' @param large_n *boolean* || defaults to `FALSE`
#'
#'   For Multi-Site analyses, a boolean indicating whether the large N
#'   visualization, intended for a high volume of sites, should be used. This
#'   visualization will produce high level summaries across all sites, with an
#'   option to add specific site comparators via the `large_n_sites` parameter.
#'
#' @param large_n_sites *vector* || defaults to `NULL`
#'
#'   When `large_n = TRUE`, a vector of site names that can add site-level information
#'   to the plot for comparison across the high level summary information
#'
#' @return This function will produce a graph to visualize the results
#'         from `prc_process` based on the parameters provided. The default
#'         output is typically a static ggplot or gt object, but interactive
#'         elements can be activated by passing the plot through `make_interactive_squba`.
#'         For a more detailed description of output specific to each check type,
#'         see the PEDSpace metadata repository
#'
#' @example inst/example-prc_process_output.R
#'
#' @export
#'
prc_output <- function(process_output,
                       dist_from_stat = 'mean',
                       event_filter = NULL,
                       large_n = FALSE,
                       large_n_sites = NULL){

  # extract output function
  output_function <- process_output %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()


  if(output_function == 'prc_ss_exp_cs'){

    prc_output <- prc_ss_exp_cs(process_output = process_output)

  }else if(output_function == 'prc_ms_exp_cs'){

    prc_output <- prc_ms_exp_cs(process_output = process_output,
                                large_n = large_n,
                                large_n_sites = large_n_sites)

  }else if(output_function == 'prc_ss_anom_cs'){

    prc_output <- prc_ss_anom_cs(process_output = process_output)

  }else if(output_function == 'prc_ms_anom_cs'){

    prc_output <- prc_ms_anom_cs(process_output = process_output,
                                 large_n = large_n,
                                 large_n_sites = large_n_sites)

  }else if(output_function == 'prc_ss_exp_la'){

    prc_output <- prc_ss_exp_la(process_output = process_output)

  }else if(output_function == 'prc_ms_exp_la'){

    prc_output <- prc_ms_exp_la(process_output = process_output,
                                dist_from_stat = dist_from_stat,
                                large_n = large_n,
                                large_n_sites = large_n_sites)

  }else if(output_function == 'prc_ss_anom_la'){

    prc_output <- prc_ss_anom_la(process_output = process_output,
                                 event_filter = event_filter)

  }else if(output_function == 'prc_ms_anom_la'){

    prc_output <- prc_ms_anom_la(process_output = process_output,
                                 event_filter = event_filter,
                                 large_n = large_n,
                                 large_n_sites = large_n_sites)

  }else{cli::cli_abort('Please enter a valid output function for this check type.')}

  return(prc_output)

}
